
# CONSTANTS
POPULATION_SIZE = 100
TARGET_GENERATION = 1000
TARGET_FITNESS = 0.9

SELECTION_METHOD = "tournament"
CROSSOVER_CHANCE = 0.8
MUTATION_CHANCE = 0.2
ELITISM_CHOSEN_INDIVIDUAL_AMOUNT = 5
REMAINDER_POPULATION = POPULATION_SIZE - ELITISM_CHOSEN_INDIVIDUAL_AMOUNT
RNG_SEED = 42

# Para el funcionamiento del modelo de machine learning
WIND_SPEED = 5.0

GRID_COLS = 10
GRID_ROWS = 10
GRID_CELL_SIZE = 25.0
GRID_START = (0, 0)
GRID_GOAL = (9, 9)

# Configuracion de poblacion inicial
USE_DIAGONALS = False  # Si se permiten movimientos diagonales
MAX_INITIAL_DETOURS = 3
MAX_GREEDY_CONNECT_STEPS = 5