
# CONSTANTS
POPULATION_SIZE = 50
TARGET_GENERATION = 100
TARGET_FITNESS = 1

SELECTION_METHOD = "tournament"
CROSSOVER_CHANCE = 0.75
MUTATION_CHANCE = 0.30
TOURNAMENT_PERCENTAGE = 0.4

ELITISM_CHOSEN_INDIVIDUAL_AMOUNT = 0
REMAINDER_POPULATION = POPULATION_SIZE - ELITISM_CHOSEN_INDIVIDUAL_AMOUNT

# Para el funcionamiento del modelo de machine learning
WIND_SPEED = 10.7
WIND_ANGLE = 270.66 # 0.0 NORTE, 90.0 ESTE, 180.0 SUR, 270 OESTE

GRID_COLS = 50
GRID_ROWS = 50
GRID_CELL_SIZE = 20 #en metros
GRID_START = (25, 0)
GRID_GOAL = (25, GRID_COLS - 1)


# Configuracion de poblacion inicial
FRACTION_WITH_MANHATTAN_PATH = 0.3

MAX_INITIAL_DETOURS = 3
MAX_GREEDY_CONNECT_STEPS = 5

#Para calcular efectos de la corriente del rio
DISTANCE_TRAVELED_TO_DRIFT_RATIO = 0.4 #Cada un metro avanzado se desplaza 0.5 m hacia abajo en y 